name: Feature Request
description: Suggest a new feature or improvement for ReleaseCraft
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make ReleaseCraft better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem
      placeholder: "I would like ReleaseCraft to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried..."

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would this feature improve your workflow?
      options:
        - Critical - Blocks my work
        - High - Significant improvement
        - Medium - Nice to have
        - Low - Minor convenience
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario where this feature would be useful
      placeholder: |
        Example:
        1. I maintain 5 open-source projects
        2. I need to generate release notes weekly
        3. This feature would save me X hours per week

  - type: textarea
    id: example
    attributes:
      label: Example
      description: If applicable, provide an example command or output
      render: shell
      placeholder: |
        # Example command
        releasecraft --format json --template custom.json

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (screenshots, links, references)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: This feature aligns with ReleaseCraft's core purpose (automated release notes generation)
          required: true
